In [1]:
# Import necessary libraries
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from keras.models import Sequential
from keras.layers import Dense
from keras.utils import to_categorical

In [33]:
# Load the Iris dataset
iris = datasets.load_iris()
X = iris.data
y = iris.target
print(type(X))
# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=100)
print(iris.target)
 

<class 'numpy.ndarray'>
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [3]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Convert labels to one-hot encoding
encoder = LabelEncoder()
y_train = to_categorical(encoder.fit_transform(y_train))
y_test = to_categorical(encoder.transform(y_test))

In [4]:
# Build the neural network model
model = Sequential()
model.add(Dense(8, input_dim=4, activation='softmax'))
model.add(Dense(3, activation='softmax'))

In [5]:
# Compile the model
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

# Train the model
model.fit(X_train, y_train, epochs=50, batch_size=10, validation_split=0.2, verbose=2)

Epoch 1/50
10/10 - 2s - loss: 1.1012 - accuracy: 0.2500 - val_loss: 1.1273 - val_accuracy: 0.1250 - 2s/epoch - 237ms/step
Epoch 2/50
10/10 - 0s - loss: 1.0940 - accuracy: 0.2812 - val_loss: 1.1194 - val_accuracy: 0.1667 - 107ms/epoch - 11ms/step
Epoch 3/50
10/10 - 0s - loss: 1.0870 - accuracy: 0.3125 - val_loss: 1.1114 - val_accuracy: 0.1667 - 106ms/epoch - 11ms/step
Epoch 4/50
10/10 - 0s - loss: 1.0803 - accuracy: 0.3333 - val_loss: 1.1041 - val_accuracy: 0.2083 - 124ms/epoch - 12ms/step
Epoch 5/50
10/10 - 0s - loss: 1.0735 - accuracy: 0.3750 - val_loss: 1.0960 - val_accuracy: 0.2083 - 148ms/epoch - 15ms/step
Epoch 6/50
10/10 - 0s - loss: 1.0667 - accuracy: 0.3958 - val_loss: 1.0889 - val_accuracy: 0.2500 - 97ms/epoch - 10ms/step
Epoch 7/50
10/10 - 0s - loss: 1.0602 - accuracy: 0.4375 - val_loss: 1.0825 - val_accuracy: 0.2917 - 176ms/epoch - 18ms/step
Epoch 8/50
10/10 - 0s - loss: 1.0531 - accuracy: 0.4375 - val_loss: 1.0748 - val_accuracy: 0.2917 - 115ms/epoch - 11ms/step
Epoch 9/50


In [6]:
loss, accuracy = model.evaluate(X_test, y_test)
print(f'Test Loss: {loss}, Test Accuracy: {accuracy}')

1/1 [==============================] - 0s 39ms/step - loss: 0.7033 - accuracy: 0.9000
Test Loss: 0.7033169865608215, Test Accuracy: 0.8999999761581421


In [31]:
import numpy as np
predict=model.predict(X_test)
print(type(predict))
print(predict)
class_label = {0: 'class_0', 1: 'class_1', 2: 'class_2'} 
predicted_class = np.argmax(predict,axis=1)
print(predicted_class)

Cluster_label = [class_label[num] for num in predicted_class]
print(Cluster_label)



1/1 [==============================] - 0s 17ms/step
<class 'numpy.ndarray'>
[[0.16174516 0.3946891  0.4435658 ]
 [0.6366139  0.22574188 0.1376442 ]
 [0.18135811 0.36701643 0.45162547]
 [0.6474505  0.21008919 0.14246039]
 [0.17366317 0.4101536  0.4161832 ]
 [0.18543181 0.3557482  0.4588199 ]
 [0.6520242  0.21370408 0.13427164]
 [0.6054303  0.24499562 0.14957409]
 [0.18843329 0.37850025 0.43306655]
 [0.604719   0.24565795 0.14962308]
 [0.63807863 0.22433059 0.1375908 ]
 [0.17072514 0.38286972 0.4464052 ]
 [0.6262935  0.22998498 0.14372157]
 [0.63028824 0.22737935 0.14233251]
 [0.16496076 0.38618112 0.4488581 ]
 [0.22951518 0.39503345 0.3754514 ]
 [0.1864844  0.48348886 0.33002678]
 [0.19834019 0.3806322  0.4210275 ]
 [0.19181304 0.36162028 0.44656664]
 [0.17581452 0.3773917  0.44679374]
 [0.20375831 0.3491194  0.4471223 ]
 [0.6149473  0.23349613 0.1515565 ]
 [0.16267867 0.42194495 0.4153764 ]
 [0.62739605 0.23199067 0.14061326]
 [0.21479762 0.4382937  0.34690878]
 [0.19197251 0.39165935 

In [37]:
import pandas as pd
df_class_results = pd.DataFrame({'ANN_class': Cluster_label, 'Test_cat': y_test})

cross_tab = pd.crosstab(df_class_results['ANN_class'], df_class_results['Test_cat'])

# Print the cross-tab
print(cross_tab)
df_class_results.head()

Test_cat    0  1   2
ANN_class           
class_0    11  0   0
class_1     0  4   1
class_2     0  2  12


ANN_class  Test_cat
0   class_2         2
1   class_0         0
2   class_2         2
3   class_0         0
4   class_2         2